# Project information
site_name: Apostila de Arduino IEEE UFABC
site_description: Apostila de Arduino IEEE UFABC
site_author: Ramo estudantil IEEE UFABC
site_url: https://github.com/IEEEUFABC/apostila_arduino

# Repository
repo_name: IEEEUFABC/apostila_arduino
repo_url: https://github.com/IEEEUFABC/apostila_arduino

# Copyright
copyright: 'Copyright &copy; 2017 - 2018 IEEE UFABC'

# Theme directory
theme_dir: material
# Options
extra:
  feature:
    tabs: false
  palette:
    primary: blue
    accent: blue

# Extensions
markdown_extensions:
  - markdown.extensions.admonition
  - markdown.extensions.codehilite(guess_lang=false)
  - markdown.extensions.attr_list
  - markdown.extensions.def_list
  - markdown.extensions.footnotes
  - markdown.extensions.meta
  - markdown.extensions.toc(permalink=true)
  - markdown.extensions.tables
  - markdown.extensions.abbr
  - markdown.extensions.smarty
  - pymdownx.arithmatex
  - pymdownx.betterem(smart_enable=all)
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist(custom_checkbox=true)
  - pymdownx.tilde
  - pymdownx.details
  - pymdownx.extrarawhtml
  - pymdownx.progressbar
pages:
  - Início: index.md
  - Teoria:
    - Arduino Uno: Teoria/ArduinoUno.md
    - Programação: Teoria/Programacao.md
  - Projetos:
    - Projetos: Projetos/projetos.md
    - Ultrassom: Projetos/PROJETO14-ULTRASSOM.md
    - Scanner: Projetos/PROJETO15-SCANNER.md
    - Extra 1 - Blink Millis: Projetos/Extra1-BlinkMillis.md
    - Extra 2 - Farol Vetor: Projetos/Extra2-FarolVetor.md

extra_css:
  - extra.css
extra_javascript:
  - extra.js

extra_css:
  - extra.css
  - extra1.css
extra_javascript:
  - extra.js
  - extra1.js
